

spring:
  h2:
    console:
      enabled: true
      path: /h2
      
  # datasource 설정
  # 파일저장으로 바꾸고 경로 및 데이터베이스 이름을 설정
  # jdbc:h2:file > in-memory가 아닌 file로 저장하고자 할때 설정 값
  # /Users/leo/Downloads/ > 파일을 저장할 경로
  # /h2-test > 데이터베이스 이름
  # 사용자이름과 비밀번호 설정 지금은 설정하지 않는다.
  datasource:
    url: jdbc:h2:file:/Users/leo/Downloads/h2-test  
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # 영속성을 가지기 위해서는 아래와 같이 ddl-auto옵션을 update로 설정
  jpa:
    hibernate:
      ddl-auto: update