

spring:
  # Set the H2 database console
  h2:
    console:
      enabled: true
      path: /h2
      
  # Set datasource
  datasource:
    url: jdbc:h2:file:/Users/leo/Downloads/h2-test
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  # Set the JPA / Hibernate
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
    hibernate:
      ddl-auto: update
      
  application:
    name: BASIC
    
management:
  endpoints:
    web:
      exposure:
        include:
        - env 